version: '3'
services:
  product_offer_db:
    container_name: local_container
    image: postgres:11.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    